FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y curl gnupg ca-certificates build-essential && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 2567

CMD ["npm", "run", "dev"]
